### PR TITLE
Remove documentation for placeholder function "hello" (+ some R CMD check issues)

### LINKED ISSUE #1: Documentation for `hello()` should be deleted
If you look at the help for packtools you'll see documentation for a function called `hello()` that does not exist:

https://github.com/BAAQMD/packtools/blob/master/man/hello.Rd

I believe that this is the default function created when you create a new package. It appears that there is no code for this function in the codebase, though - Just the documentation. 

This documentation was probably just included in error.

### PR DESCRIPTION
**Pull request by arilamstein**
Also rerun roxygenize(), which lead to two minor changes.

Fixes #1.

### CODE REVIEW

**Review by dholstius — APPROVED** [review]

**Review by dholstius — APPROVED** [review]
Approved! @arilamstein can you merge and install site-wide? (Not sure if you have perms to install site-wide or not ... if not, maybe @ydu0316 can assist?)

**Comment by arilamstein** [comment]
> Approved! @arilamstein can you merge and install site-wide? (Not sure if you have perms to install site-wide or not ... if not, maybe @ydu0316 can assist?)

I have merged this. Unfortunately I don't know how to install. @ydu0316 Can you help me with that?

**Comment by ydu0316** [comment]
Sure. I can install the package site-wide. @arilamstein

**Comment by ydu0316** [comment]
Also, should we update the version # in `DESCRIPTION` as well? @arilamstein @dholstius

**Comment by arilamstein** [comment]
> Also, should we update the version # in `DESCRIPTION` as well? @arilamstein @dholstius

I can increment the version now. I'll report back when it's done.

**Comment by arilamstein** [comment]
> Also, should we update the version # in `DESCRIPTION` as well? @arilamstein @dholstius

The version in the `DESCRIPTION` file in master should now be today's date.

**Comment by ydu0316** [comment]
> > Also, should we update the version # in `DESCRIPTION` as well? @arilamstein @dholstius
> 
> The version in the `DESCRIPTION` file in master should now be today's date.

Version 2021.07.14 is now installed.

**Pull request merged**
